services:
  # Backend Service
  - type: web
    name: tess-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: test
      - key: DB_PORT
        value: 3306

  # Frontend (React, Vite, etc.)
  - type: static
    name: tess-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    autoDeploy: true
